version: "3.8"

services:
  msitu-technoogies-company-profile:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: msitu-technoogies-company-profile
    ports:
      - "3005:3000"
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
    command: pnpm dev
    restart: unless-stopped

